name: "Automated Release Notes Generator"
description: "Drafts GitHub Releases from Conventional Commit PR titles when a tag is pushed."
author: "firasmosbehi"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github-token:
    description: "GitHub token with repo scope (typically secrets.GITHUB_TOKEN)."
    required: true
  tag:
    description: "Tag name to draft release for. Defaults to the tag that triggered the workflow."
    required: false
  dry-run:
    description: "If true, skip creating/updating the release and just emit the body."
    required: false
    default: "false"
  heading-level:
    description: "Markdown heading level for category sections (e.g., 2 -> ##)."
    required: false
    default: "2"
  base:
    description: "Optional ref/sha to use as comparison base instead of previous tag (useful for hotfixes or first releases)."
    required: false
  head:
    description: "Optional ref/sha to use as comparison head instead of the current tag."
    required: false
  empty-message:
    description: "Message to use when no categorized changes are found."
    required: false
    default: "No categorized changes found."
  template:
    description: "Release notes template. Supports {{sections}}, {{tag}}, {{previousTag}} placeholders."
    required: false
    default: "{{sections}}"
  category-map:
    description: "JSON object mapping Conventional Commit types to headings (e.g., {\"perf\":\"Performance\"})."
    required: false
outputs:
  release-body:
    description: "Rendered release notes body."
branding:
  icon: "tag"
  color: "green"
